#!/bin/bash

set -e
supported_languages="cs_CZ"
root="`dirname \"$0\"`/.."
cd $root
wp i18n make-pot . i18n/wmcz-plugin.pot --skip-js
sed -n '1p;2p' i18n/wmcz-plugin.pot > /tmp/$$
echo "#, fuzzy" >> /tmp/$$
sed '1d;2d' i18n/wmcz-plugin.pot >> /tmp/$$
mv /tmp/$$ i18n/wmcz-plugin.pot

cd i18n
for lang in $supported_languages; do
	msgmerge --backup=off --update wmcz-plugin-$lang.po wmcz-plugin.pot
done
